

services:
  nginx:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
  api:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
