

services:
  nginx:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  api:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
